<%
require 'yaml'
formula = YAML.load_file('metadata.yml')
formula_name = formula['name']
%>
---
driver:
  name: vagrant
  use_sudo: false

platforms:
- name: ubuntu-18.04

provisioner:
  name: salt_solo
  formula: minio
  pillars-from-files:
    minio.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
           - minio

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  <% if ENV['SALT_BOOTSTRAP_URL'] %>
  salt_bootstrap_url: <%= ENV['SALT_BOOTSTRAP_URL'] %>
  <% end %>
  salt_copy_filter:
    - .kitchen
    - .git
    - .ssh
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  salt_version: latest
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

suites:
  - name: default
