<%
require 'yaml'
formula = YAML.load_file('metadata.yml')
formula_name = formula['name']
%>
---
driver:
  name: vagrant
  use_sudo: false

platforms:
# Latest distros
#- name: debian-9
- name: ubuntu-18.04
  #- name: centos-7
  #- name: fedora-29
  #- name: opensuse-42.3
  #driver:
  #  run_command: /usr/lib/systemd/systemd
  #  provision_command:
  #    - systemctl enable sshd.service

provisioner:
  name: salt_solo
  formula: minio
  pillars-from-files:
    minio.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
           - minio

provisioner:
  name: salt_solo
  salt_install: bootstrap
  #salt_bootstrap_options: -p git -p curl -p ca_root_nss -p py27-pip -p python
  salt_version: latest
  <% if ENV['SALT_BOOTSTRAP_URL'] %>
  salt_bootstrap_url: <%= ENV['SALT_BOOTSTRAP_URL'] %>
  <% end %>
  salt_copy_filter:
    - .kitchen
    - .git
    - .ssh
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  salt_version: latest
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

suites:
  - name: default
